export const ATTACK_TO_OPPONENT = {
  normal: {
    rock: "notEffective",
    ghost: "noEffect",
    steel: "notEffective",
  },
  fire: {
    fire: "notEffective",
    water: "notEffective",
    grass: "effective",
    ice: "effective",
    bug: "effective",
    rock: "notEffective",
    dragon: "notEffective",
    steel: "effective",
  },
  water: {
    fire: "effective",
    water: "notEffective",
    grass: "notEffective",
    ground: "effective",
    rock: "effective",
    dragon: "notEffective",
  },
  electric: {
    water: "effective",
    electric: "notEffective",
    grass: "notEffective",
    ground: "noEffect",
    flying: "effective",
    dragon: "notEffective",
  },
  grass: {
    fire: "notEffective",
    water: "effective",
    grass: "notEffective",
    poison: "notEffective",
    ground: "effective",
    flying: "notEffective",
    bug: "notEffective",
    rock: "effective",
    dragon: "notEffective",
    steel: "notEffective",
  },
  ice: {
    fire: "notEffective",
    water: "notEffective",
    grass: "effective",
    ground: "effective",
    flying: "effective",
    dragon: "effective",
    steel: "notEffective",
  },
  fighting: {
    normal: "effective",
    ice: "effective",
    rock: "effective",
    dark: "effective",
    steel: "effective",
    poison: "notEffective",
    flying: "notEffective",
    psychic: "notEffective",
    bug: "notEffective",
    fairy: "notEffective",
    ghost: "noEffect",
  },
  poison: {
    grass: "effective",
    poison: "notEffective",
    ground: "notEffective",
    rock: "notEffective",
    ghost: "notEffective",
    steel: "noEffect",
    fairy: "effective",
  },
  ground: {
    fire: "effective",
    electric: "effective",
    grass: "notEffective",
    poison: "effective",
    flying: "noEffect",
    bug: "notEffective",
    rock: "effective",
    steel: "effective",
  },
  flying: {
    electric: "notEffective",
    grass: "effective",
    fighting: "effective",
    bug: "effective",
    rock: "notEffective",
    steel: "notEffective",
  },
  psychic: {
    fighting: "effective",
    poison: "effective",
    psychic: "notEffective",
    dark: "noEffect",
    steel: "notEffective",
  },
  bug: {
    fire: "notEffective",
    grass: "effective",
    fighting: "notEffective",
    poison: "notEffective",
    flying: "notEffective",
    psychic: "effective",
    ghost: "notEffective",
    dark: "effective",
    steel: "notEffective",
    fairy: "notEffective",
  },
  rock: {
    fire: "effective",
    ice: "effective",
    fighting: "notEffective",
    ground: "notEffective",
    flying: "effective",
    bug: "effective",
    steel: "notEffective",
  },
  ghost: {
    normal: "noEffect",
    psychic: "effective",
    ghost: "effective",
    dark: "notEffective",
  },
  dragon: {
    dragon: "effective",
    steel: "notEffective",
    fairy: "noEffect",
  },
  dark: {
    fighting: "notEffective",
    psychic: "effective",
    ghost: "effective",
    dark: "notEffective",
    fairy: "notEffective",
  },
  steel: {
    fire: "notEffective",
    water: "notEffective",
    electric: "notEffective",
    ice: "effective",
    rock: "effective",
    fairy: "effective",
    steel: "notEffective",
  },
  fairy: {
    fire: "notEffective",
    fighting: "effective",
    poison: "notEffective",
    dragon: "effective",
    dark: "effective",
    steel: "notEffective",
  },
};
